//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ExpenseAccount
    {
        public int Id { get; set; }
        public string EANumber { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> OccurDate { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public Nullable<int> CateId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Creater { get; set; }
        public string Modifier { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public decimal SumMoney { get; set; }
        public int ApproveStatus { get; set; }
        public string RefusedMessage { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    }
}
