//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_ExpenseAccount_Detail
    {
        public int Id { get; set; }
        public int ExpenseAccountId { get; set; }
        public System.DateTime OccurDate { get; set; }
        public string Remark { get; set; }
        public int CateId { get; set; }
        public decimal Money { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
        public string Creater { get; set; }
        public string Modifier { get; set; }
        public int CompanyId { get; set; }
    }
}
