//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_System_Feedback
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string Url { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ReplyMessage { get; set; }
        public int Creater { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModefyDate { get; set; }
    }
}
