//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_User_Right
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public bool Permit { get; set; }
        public System.DateTime ModifeTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ProgramId { get; set; }
    
        public virtual EM_User_Account EM_User_Account { get; set; }
        public virtual EM_System_Program EM_System_Program { get; set; }
    }
}
