//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EM_User_Login_Record
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string LoginInfo { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public string ErrorInfo { get; set; }
    }
}
