//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EM.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMDB : DbContext
    {
        public EMDB()
            : base("name=EMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EM_User_Account> EM_User_Account { get; set; }
        public virtual DbSet<EM_User_Login_Record> EM_User_Login_Record { get; set; }
        public virtual DbSet<EM_System_Program> EM_System_Program { get; set; }
        public virtual DbSet<EM_Charge_Cate> EM_Charge_Cate { get; set; }
        public virtual DbSet<EM_Company> EM_Company { get; set; }
        public virtual DbSet<EM_Company_Performance> EM_Company_Performance { get; set; }
        public virtual DbSet<EM_ExpenseAccount> EM_ExpenseAccount { get; set; }
        public virtual DbSet<EM_System_ActionLog> EM_System_ActionLog { get; set; }
        public virtual DbSet<EM_ExpenseAccount_File> EM_ExpenseAccount_File { get; set; }
        public virtual DbSet<EM_ExpenseAccount_ApproveHistory> EM_ExpenseAccount_ApproveHistory { get; set; }
        public virtual DbSet<EM_ExpenseAccount_Detail> EM_ExpenseAccount_Detail { get; set; }
        public virtual DbSet<EM_Company_Limit> EM_Company_Limit { get; set; }
        public virtual DbSet<EM_User_Right> EM_User_Right { get; set; }
        public virtual DbSet<EM_User_Role> EM_User_Role { get; set; }
    }
}
